coverage:
  status:
    project:
      default:
        target: auto  # auto compares coverage to the previous base commit
        threshold: 1%
        branches:
          - master
comment:
  layout: "reach, diff, flags, files"  # Remove items here to change the format