name: test
channels:
  - conda-forge
dependencies:
  - pip
  - backoff>=1.10.0
  - geojson
  - requests
  - geopandas
  - turfpy>=0.0.3
  - geobuf
  - ijson==3.1.1
  - pip:
    - "-r ../../requirements.txt"
    - "-r ../../requirements_dev.txt"