name: xyzspaces
channels:
  - conda-forge
dependencies:
  - bqplot
  - here-map-widget-for-jupyter>=1.1.1
  - ipyleaflet
  - sidecar
  - pip
  - pip:
    - "-r ../requirements.txt"
    - "-r ../requirements_dev.txt"
    - "-e ../"
