name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test
        mamba-version: "*"
        channels: conda-forge

    - name: Conda install dependencies
      shell: bash -l {0}
      run: |
        conda env update --file ci/env/environment.yml --name test

    - name: Lint check
      shell: bash -l {0}
      run: |
        make clean
        make lint
        make typing

    - name: Test check
      shell: bash -l {0}
      env:
        XYZ_TOKEN: ${{ secrets.XYZ_TOKEN }}
        HERE_USER: ${{ secrets.HERE_USER }}
        HERE_PASSWORD: ${{ secrets.HERE_PASSWORD }}
      run: |
        pytest -v --durations=10 --cov=xyzspaces tests --cov-report=xml

    - name: Upload coverage to Codecov
      if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        verbose: true

    - name: Build Docs and Changelog (Only on Linux for saving time)
      if: matrix.os == 'ubuntu-latest'
      shell: bash -l {0}
      run: |
        make draft_changelog
        sh scripts/build_docs.sh

    - name: Install xyzspaces
      shell: bash -l {0}
      run: pip install .[dev]